name: Windows x64 打包與發布
on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  
jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: 設置 .NET 環境
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0 # 請根據您的專案需要調整版本
    
    - name: 安裝 Velopack CLI
      run: dotnet tool update -g vpk
    
    - name: 取得版本號
      id: get_version
      shell: pwsh
      run: |
        $version = "1.0.0"
        if ("${{ github.ref }}" -match "refs/tags/v(.*)") {
          $version = $Matches[1]
        }
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    
    - name: 還原相依套件
      run: dotnet restore AvaloniaDemo.Desktop/AvaloniaDemo.Desktop.csproj
    
    - name: 建置專案
      run: dotnet build AvaloniaDemo.Desktop/AvaloniaDemo.Desktop.csproj --configuration Release --no-restore
    
    - name: 發布 AvaloniaDemo.Desktop 專案
      run: dotnet publish AvaloniaDemo.Desktop/AvaloniaDemo.Desktop.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true -o ./publish/win-64
    
    - name: Velopack 打包
      run: vpk pack -u AvaloniaDemo -v ${{ steps.get_version.outputs.VERSION }} -f net8.0-x64-runtime -p ./publish/win-64 -o ./artifacts/win-64 -e AvaloniaDemo.Desktop.exe
    
    - name: 壓縮為 zip
      run: |
        Compress-Archive -Path ./artifacts/win-64/* -DestinationPath ./win64-${{ steps.get_version.outputs.VERSION }}.zip -Force
      shell: pwsh
    
    - name: 上傳壓縮檔
      uses: actions/upload-artifact@v4
      with:
        name: win64-${{ steps.get_version.outputs.VERSION }}
        path: ./win64-${{ steps.get_version.outputs.VERSION }}.zip
    
    # 只發佈壓縮檔到 GitHub Release
    - name: 建立 GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: 版本 ${{ steps.get_version.outputs.VERSION }}
        files: ./win64-${{ steps.get_version.outputs.VERSION }}.zip
        body: |
          ## AvaloniaDemo 版本 ${{ steps.get_version.outputs.VERSION }}
          
          ### 下載與安裝說明
          
          這是針對 Windows x64 平台的發布版本。
          
          - 下載 `win64-${{ steps.get_version.outputs.VERSION }}.zip` 取得完整應用程式包
          
        # 設置為 false 可以禁止自動添加源代碼
        generate_release_notes: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
